### ISSUE TITLE
how to start server?

### ISSUE THREAD

**Issue by RandomTNT** [rickparrish/GameSrv#2]
I really dont  know how to start the server

**Comment by rickparrish** [comment]
On Windows running GameSrvConsole, GameSrvGUI, or GameSrvService is how you start the server.

I haven't tested with Linux in years, so while GameSrvConsole is what I used way back when, I have no idea whether it still works on modern distros.

**Comment by RandomTNT** [comment]
Thank you very much!!
Best wishes,
Kirill

пт, 13 мар. 2020 г., 5:52 rickparrish <notifications@github.com>:
