### ISSUE TITLE
Make this work in os/2

### ISSUE THREAD

**Issue by ryanfantus** [rickparrish/GameSrv#3]
Hi Rick,

A number of people (myself included) have struggled against the forward march of Windows and 16 bit game compatibility. There exists a near-perfect solution in modern incarnations of OS/2 (namely, ArcaOS). ArcaOS runs on bare metal modern hardware and offers full DOS compatibility. So...it's _close_ to being an ideal game server. However, something akin to GameSrv would be perfect.

Is there a way to get GameSrv to work in OS/2 for the purposes of making future proof doorgame servers?

**Comment by rickparrish** [comment]
Sorry, I don't know anything about OS/2.  But unless it supports the .NET Framework, no I don't think it'll be doable.

I noticed that the Synchronet docs point users to [ntvdmx64](http://www.columbia.edu/~em36/ntvdmx64.html) as a solution for running 16bit doors on 64bit Windows though, so maybe the eventual phase-out of 32bit Windows won't be a dead-end for 16bit doors after all.
